#ifndef _CURSORPREVIEW_H_
#define _CURSORPREVIEW_H_

	#include "SharedCode.h"

	#define WS_CURSORPREVIEW ( WS_BORDER | WS_CAPTION | WS_SYSMENU | WS_CLIPCHILDREN | WS_CLIPSIBLINGS | WS_THICKFRAME )
	#define WX_CURSORPREVIEW ( WS_EX_TOOLWINDOW )

	#include "CursorShop.h"

#endif // _CLIENTSPACE_H_
