#ifndef _CURSORFACTORYLOOK_H_
#define _CURSORFACTORYLOOK_H_

	#define CF_BLACK 0x000000
	#define CF_WHITE 0xFFFFFF

	#define CF_CURSOR_XSIZE 40
	#define CF_CURSOR_YSIZE 30

	#define CF_ENLARGE_FACTOR 5
	#define CF_BORDER_WIDTH 1.0f
	#define CF_SHADOW_DIST 3

#endif // _CURSORFACTORYLOOK_H_
